# -*- coding: utf-8 -*-
"""Thera.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hANK2167yL3iuwButNBZKkoM654-Btrj
"""

!pip install gradio

!pip install openai

import openai
import gradio

openai.api_key = "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"

messages = [{"role": "system",
             "content": "You are a professional therapist and nutritional Psychologist. You are very friendly and empathetic. You are very consise too"}]


def CustomChatGPT(user_input):
    messages.append({"role": "user", "content": user_input})
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages
    )
    ChatGPT_reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": ChatGPT_reply})
    return ChatGPT_reply


demo = gradio.Interface(fn=CustomChatGPT, inputs="text", outputs="text", title="Thera")

demo.launch(share=True)

import openai
import gradio

openai.api_key = "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"

messages = [{"role": "system",
             "content": "You are a professional therapist and nutritional Psychologist"}]


def CustomChatGPT(user_input):
    messages.append({"role": "user", "content": user_input})
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages
    )
    ChatGPT_reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": ChatGPT_reply})
    return ChatGPT_reply
def chatbot_interface(image, textbox):
    # Display the image in the middle of the screen
    image_html = f'<img src="{gh.jpg}" style="display: block; margin-left: auto; margin-right: auto;">'
    return image_html, CustomChatGPT(textbox)


demo = gradio.Interface(fn=CustomChatGPT, inputs="text", outputs="text", title="Boo")

demo.launch()

